// Mock data for Guardian Intel development
// This will be replaced with real API calls and database queries

export interface Customer {
  id: string;
  firstName: string;
  lastName: string;
  email: string | null;
  phone: string | null;
  address: string;
  city: string;
  state: string;
  zipCode: string;
  propertyType: string | null;
  yearBuilt: number | null;
  squareFootage: number | null;
  roofType: string | null;
  roofAge: number | null;
  propertyValue: number | null;
  insuranceCarrier: string | null;
  policyType: string | null;
  deductible: number | null;
  leadScore: number;
  // Legacy score fields - now calculated dynamically by scoring service
  // Kept for backwards compatibility and as reference data
  urgencyScore?: number | null;
  profitPotential?: number | null;
  churnRisk?: number | null;
  status: string;
  stage: string;
  assignedRep?: string | { id: string; name: string; email: string } | null;
  lastContact?: Date | string;
  nextAction?: string;
  nextActionDate?: Date | string;
  createdAt?: string;
  updatedAt?: string;
}

export interface IntelItem {
  id: string;
  customerId: string;
  source: string;
  category: string;
  title: string;
  content: string;
  confidence: number;
  actionable: boolean;
  priority: "low" | "medium" | "high" | "critical";
  createdAt: Date;
}

export interface WeatherEvent {
  id: string;
  customerId: string | null;
  eventType: string;
  eventDate: Date | string;
  severity: string;
  hailSize?: number | null;
  windSpeed?: number | null;
  damageReported: boolean;
  claimFiled: boolean;
}

// Guardian Roofing & Siding - Service Areas: PA, NJ, DE, MD, VA, NY
// Main HQ: Southampton, PA 18966 | VA HQ: Fredericksburg, VA 22401
// Contact: 1-855-424-5911 (PA) | 1-540-425-6770 (VA)

export const mockCustomers: Customer[] = [
  {
    id: "1",
    firstName: "Michael",
    lastName: "Henderson",
    email: "m.henderson@email.com",
    phone: "(215) 234-5678",
    address: "4521 Oak Ridge Drive",
    city: "Southampton",
    state: "PA",
    zipCode: "18966",
    propertyType: "Single Family",
    yearBuilt: 1998,
    squareFootage: 2850,
    roofType: "Asphalt Shingle",
    roofAge: 18,
    propertyValue: 425000,
    insuranceCarrier: "State Farm",
    policyType: "HO-3",
    deductible: 2500,
    leadScore: 92,
    urgencyScore: 88,
    profitPotential: 18500,
    churnRisk: 12,
    status: "prospect",
    stage: "qualified",
    assignedRep: "Sarah Mitchell",
    lastContact: new Date("2026-01-05"),
    nextAction: "Schedule inspection",
    nextActionDate: new Date("2026-01-08"),
  },
  {
    id: "2",
    firstName: "Jennifer",
    lastName: "Walsh",
    email: "j.walsh@email.com",
    phone: "(215) 345-6789",
    address: "892 Maple Street",
    city: "Doylestown",
    state: "PA",
    zipCode: "18901",
    propertyType: "Single Family",
    yearBuilt: 2005,
    squareFootage: 3200,
    roofType: "Architectural Shingle",
    roofAge: 12,
    propertyValue: 525000,
    insuranceCarrier: "Allstate",
    policyType: "HO-5",
    deductible: 1000,
    leadScore: 78,
    urgencyScore: 65,
    profitPotential: 22000,
    churnRisk: 25,
    status: "lead",
    stage: "contacted",
    assignedRep: "James Rodriguez",
    lastContact: new Date("2026-01-04"),
    nextAction: "Follow-up call",
    nextActionDate: new Date("2026-01-07"),
  },
  {
    id: "3",
    firstName: "Robert",
    lastName: "Chen",
    email: "r.chen@email.com",
    phone: "(215) 456-7890",
    address: "1245 Birch Lane",
    city: "Bensalem",
    state: "PA",
    zipCode: "19020",
    propertyType: "Single Family",
    yearBuilt: 1992,
    squareFootage: 2400,
    roofType: "3-Tab Shingle",
    roofAge: 24,
    propertyValue: 375000,
    insuranceCarrier: "Progressive",
    policyType: "HO-3",
    deductible: 2000,
    leadScore: 95,
    urgencyScore: 94,
    profitPotential: 16500,
    churnRisk: 8,
    status: "prospect",
    stage: "proposal",
    assignedRep: "Sarah Mitchell",
    lastContact: new Date("2026-01-06"),
    nextAction: "Send proposal",
    nextActionDate: new Date("2026-01-07"),
  },
  {
    id: "4",
    firstName: "Amanda",
    lastName: "Foster",
    email: "a.foster@email.com",
    phone: "(540) 567-8901",
    address: "3678 Pine Valley Court",
    city: "Fredericksburg",
    state: "VA",
    zipCode: "22401",
    propertyType: "Single Family",
    yearBuilt: 2010,
    squareFootage: 4100,
    roofType: "Metal Standing Seam",
    roofAge: 8,
    propertyValue: 685000,
    insuranceCarrier: "USAA",
    policyType: "HO-5",
    deductible: 5000,
    leadScore: 45,
    urgencyScore: 30,
    profitPotential: 35000,
    churnRisk: 55,
    status: "lead",
    stage: "new",
    assignedRep: "James Rodriguez",
    lastContact: new Date("2026-01-03"),
    nextAction: "Initial outreach",
    nextActionDate: new Date("2026-01-09"),
  },
  {
    id: "5",
    firstName: "David",
    lastName: "Martinez",
    email: "d.martinez@email.com",
    phone: "(215) 678-9012",
    address: "567 Walnut Street",
    city: "Newtown",
    state: "PA",
    zipCode: "18940",
    propertyType: "Single Family",
    yearBuilt: 1985,
    squareFootage: 1950,
    roofType: "Asphalt Shingle",
    roofAge: 28,
    propertyValue: 285000,
    insuranceCarrier: "Nationwide",
    policyType: "HO-3",
    deductible: 1500,
    leadScore: 88,
    urgencyScore: 92,
    profitPotential: 14000,
    churnRisk: 15,
    status: "customer",
    stage: "closed",
    assignedRep: "Sarah Mitchell",
    lastContact: new Date("2026-01-06"),
    nextAction: "Start production",
    nextActionDate: new Date("2026-01-10"),
  },
  // Additional customers to support all filter options
  {
    id: "6",
    firstName: "Thomas",
    lastName: "Anderson",
    email: "t.anderson@email.com",
    phone: "(555) 789-0123",
    address: "2891 Riverside Drive",
    city: "Lansdale",
    state: "PA",
    zipCode: "43221",
    propertyType: "Single Family",
    yearBuilt: 2001,
    squareFootage: 3500,
    roofType: "Architectural Shingle",
    roofAge: 15,
    propertyValue: 595000,
    insuranceCarrier: "Liberty Mutual",
    policyType: "HO-3",
    deductible: 2000,
    leadScore: 89,
    urgencyScore: 82,
    profitPotential: 24500,
    churnRisk: 18,
    status: "prospect",
    stage: "negotiation",
    assignedRep: "Sarah Mitchell",
    lastContact: new Date("2026-01-07"),
    nextAction: "Final pricing discussion",
    nextActionDate: new Date("2026-01-09"),
  },
  {
    id: "7",
    firstName: "Patricia",
    lastName: "Williams",
    email: "p.williams@email.com",
    phone: "(555) 890-1234",
    address: "445 Huntington Park",
    city: "Cherry Hill",
    state: "NJ",
    zipCode: "43212",
    propertyType: "Single Family",
    yearBuilt: 1995,
    squareFootage: 2200,
    roofType: "3-Tab Shingle",
    roofAge: 22,
    propertyValue: 345000,
    insuranceCarrier: "Farmers",
    policyType: "HO-3",
    deductible: 1500,
    leadScore: 91,
    urgencyScore: 85,
    profitPotential: 15800,
    churnRisk: 10,
    status: "prospect",
    stage: "negotiation",
    assignedRep: "James Rodriguez",
    lastContact: new Date("2026-01-06"),
    nextAction: "Address concerns about timeline",
    nextActionDate: new Date("2026-01-08"),
  },
  {
    id: "8",
    firstName: "Christopher",
    lastName: "Brown",
    email: "c.brown@email.com",
    phone: "(555) 901-2345",
    address: "1122 Summit Street",
    city: "Wilmington",
    state: "DE",
    zipCode: "43209",
    propertyType: "Single Family",
    yearBuilt: 1988,
    squareFootage: 2650,
    roofType: "Asphalt Shingle",
    roofAge: 20,
    propertyValue: 475000,
    insuranceCarrier: "State Farm",
    policyType: "HO-5",
    deductible: 2500,
    leadScore: 97,
    urgencyScore: 95,
    profitPotential: 19200,
    churnRisk: 5,
    status: "closed-won",
    stage: "closed",
    assignedRep: "Sarah Mitchell",
    lastContact: new Date("2026-01-07"),
    nextAction: "Schedule installation",
    nextActionDate: new Date("2026-01-12"),
  },
  {
    id: "9",
    firstName: "Elizabeth",
    lastName: "Davis",
    email: "e.davis@email.com",
    phone: "(555) 012-3456",
    address: "3344 Olentangy River Road",
    city: "Warminster",
    state: "PA",
    zipCode: "43214",
    propertyType: "Single Family",
    yearBuilt: 2008,
    squareFootage: 2100,
    roofType: "Architectural Shingle",
    roofAge: 10,
    propertyValue: 385000,
    insuranceCarrier: "Allstate",
    policyType: "HO-3",
    deductible: 1000,
    leadScore: 98,
    urgencyScore: 90,
    profitPotential: 17500,
    churnRisk: 3,
    status: "closed-won",
    stage: "closed",
    assignedRep: "James Rodriguez",
    lastContact: new Date("2026-01-05"),
    nextAction: "Materials ordered - await delivery",
    nextActionDate: new Date("2026-01-15"),
  },
  {
    id: "10",
    firstName: "James",
    lastName: "Wilson",
    email: "j.wilson@email.com",
    phone: "(555) 123-4567",
    address: "778 Schrock Road",
    city: "Stafford",
    state: "VA",
    zipCode: "43081",
    propertyType: "Single Family",
    yearBuilt: 2003,
    squareFootage: 2800,
    roofType: "Asphalt Shingle",
    roofAge: 14,
    propertyValue: 425000,
    insuranceCarrier: "Progressive",
    policyType: "HO-3",
    deductible: 2000,
    leadScore: 35,
    urgencyScore: 25,
    profitPotential: 21000,
    churnRisk: 85,
    status: "closed-lost",
    stage: "closed",
    assignedRep: "Sarah Mitchell",
    lastContact: new Date("2025-12-20"),
    nextAction: "Follow up in 6 months",
    nextActionDate: new Date("2026-06-20"),
  },
  {
    id: "11",
    firstName: "Linda",
    lastName: "Taylor",
    email: "l.taylor@email.com",
    phone: "(555) 234-5679",
    address: "556 Morse Road",
    city: "Baltimore",
    state: "MD",
    zipCode: "43230",
    propertyType: "Single Family",
    yearBuilt: 2000,
    squareFootage: 2300,
    roofType: "3-Tab Shingle",
    roofAge: 18,
    propertyValue: 355000,
    insuranceCarrier: "Nationwide",
    policyType: "HO-3",
    deductible: 1500,
    leadScore: 28,
    urgencyScore: 20,
    profitPotential: 16800,
    churnRisk: 90,
    status: "closed-lost",
    stage: "closed",
    assignedRep: "James Rodriguez",
    lastContact: new Date("2025-12-15"),
    nextAction: "Lost to competitor - review pricing",
    nextActionDate: new Date("2026-03-15"),
  },
  {
    id: "12",
    firstName: "Steven",
    lastName: "Garcia",
    email: "s.garcia@email.com",
    phone: "(555) 345-6780",
    address: "901 High Street",
    city: "Yonkers",
    state: "NY",
    zipCode: "43085",
    propertyType: "Single Family",
    yearBuilt: 1990,
    squareFootage: 2450,
    roofType: "Cedar Shake",
    roofAge: 25,
    propertyValue: 520000,
    insuranceCarrier: "Chubb",
    policyType: "HO-5",
    deductible: 5000,
    leadScore: 72,
    urgencyScore: 68,
    profitPotential: 42000,
    churnRisk: 30,
    status: "customer",
    stage: "qualified",
    assignedRep: "Sarah Mitchell",
    lastContact: new Date("2026-01-04"),
    nextAction: "Existing customer - upsell opportunity",
    nextActionDate: new Date("2026-01-10"),
  },
  {
    id: "13",
    firstName: "Nancy",
    lastName: "Moore",
    email: "n.moore@email.com",
    phone: "(555) 456-7891",
    address: "2234 Henderson Road",
    city: "King of Prussia",
    state: "PA",
    zipCode: "43220",
    propertyType: "Single Family",
    yearBuilt: 2012,
    squareFootage: 3100,
    roofType: "Architectural Shingle",
    roofAge: 8,
    propertyValue: 465000,
    insuranceCarrier: "Erie Insurance",
    policyType: "HO-3",
    deductible: 1000,
    leadScore: 55,
    urgencyScore: 40,
    profitPotential: 19500,
    churnRisk: 45,
    status: "lead",
    stage: "qualified",
    assignedRep: "James Rodriguez",
    lastContact: new Date("2026-01-03"),
    nextAction: "Qualify budget and timeline",
    nextActionDate: new Date("2026-01-08"),
  },
  {
    id: "14",
    firstName: "Kevin",
    lastName: "Thompson",
    email: "k.thompson@email.com",
    phone: "(555) 567-8902",
    address: "4456 Sawmill Road",
    city: "Trenton",
    state: "NJ",
    zipCode: "43017",
    propertyType: "Single Family",
    yearBuilt: 1997,
    squareFootage: 3800,
    roofType: "Slate",
    roofAge: 28,
    propertyValue: 725000,
    insuranceCarrier: "AIG",
    policyType: "HO-5",
    deductible: 10000,
    leadScore: 82,
    urgencyScore: 78,
    profitPotential: 85000,
    churnRisk: 22,
    status: "prospect",
    stage: "proposal",
    assignedRep: "Sarah Mitchell",
    lastContact: new Date("2026-01-07"),
    nextAction: "Review proposal with homeowner",
    nextActionDate: new Date("2026-01-09"),
  },
  {
    id: "15",
    firstName: "Michelle",
    lastName: "Jackson",
    email: "m.jackson@email.com",
    phone: "(555) 678-9013",
    address: "887 Tuttle Crossing",
    city: "Woodbridge",
    state: "VA",
    zipCode: "43016",
    propertyType: "Single Family",
    yearBuilt: 2015,
    squareFootage: 2950,
    roofType: "Architectural Shingle",
    roofAge: 5,
    propertyValue: 545000,
    insuranceCarrier: "USAA",
    policyType: "HO-3",
    deductible: 2500,
    leadScore: 42,
    urgencyScore: 28,
    profitPotential: 23500,
    churnRisk: 65,
    status: "lead",
    stage: "new",
    assignedRep: "James Rodriguez",
    lastContact: new Date("2026-01-02"),
    nextAction: "Initial contact attempt",
    nextActionDate: new Date("2026-01-08"),
  },
];

export const mockIntelItems: IntelItem[] = [
  {
    id: "i1",
    customerId: "1",
    source: "weather-api",
    category: "weather",
    title: "Recent Hail Event Detected",
    content: "1.25 inch hail reported in area on Jan 2, 2026. High probability of roof damage based on shingle age and storm severity.",
    confidence: 94,
    actionable: true,
    priority: "critical",
    createdAt: new Date("2026-01-02"),
  },
  {
    id: "i2",
    customerId: "1",
    source: "property-api",
    category: "property",
    title: "Roof Age Exceeds Warranty",
    content: "18-year-old asphalt shingle roof. Most manufacturer warranties expire at 15-20 years. Prime candidate for replacement.",
    confidence: 100,
    actionable: true,
    priority: "high",
    createdAt: new Date("2026-01-01"),
  },
  {
    id: "i3",
    customerId: "1",
    source: "insurance-lookup",
    category: "insurance",
    title: "State Farm - Favorable Claim History",
    content: "Carrier known for smooth claims process. Customer has no prior claims in 5 years - good standing for new claim.",
    confidence: 87,
    actionable: true,
    priority: "medium",
    createdAt: new Date("2026-01-03"),
  },
  {
    id: "i4",
    customerId: "3",
    source: "weather-api",
    category: "weather",
    title: "Multiple Storm Events",
    content: "3 significant weather events in past 6 months. Wind gusts up to 65mph recorded. Recommend thorough inspection.",
    confidence: 91,
    actionable: true,
    priority: "critical",
    createdAt: new Date("2026-01-04"),
  },
  {
    id: "i5",
    customerId: "3",
    source: "property-api",
    category: "property",
    title: "Aging 3-Tab Shingles",
    content: "24-year-old 3-tab shingles significantly past expected lifespan. Visible granule loss likely. High conversion probability.",
    confidence: 95,
    actionable: true,
    priority: "high",
    createdAt: new Date("2026-01-05"),
  },
  {
    id: "i6",
    customerId: "2",
    source: "web-search",
    category: "social",
    title: "Recent Home Purchase",
    content: "Property records show home purchased 8 months ago. New homeowners often invest in improvements and maintenance.",
    confidence: 100,
    actionable: false,
    priority: "medium",
    createdAt: new Date("2026-01-02"),
  },
  {
    id: "i7",
    customerId: "5",
    source: "crm-sync",
    category: "sales",
    title: "Contract Signed - Production Ready",
    content: "Customer signed contract for full roof replacement. Materials ordered. Awaiting crew scheduling.",
    confidence: 100,
    actionable: true,
    priority: "high",
    createdAt: new Date("2026-01-06"),
  },
  // Additional intel for new customers
  {
    id: "i8",
    customerId: "6",
    source: "weather-api",
    category: "weather",
    title: "Wind Damage Potential",
    content: "60mph wind gusts recorded in Upper Arlington area. 15-year shingles may have lifted edges.",
    confidence: 88,
    actionable: true,
    priority: "high",
    createdAt: new Date("2026-01-05"),
  },
  {
    id: "i9",
    customerId: "6",
    source: "crm-sync",
    category: "sales",
    title: "Price Negotiation Active",
    content: "Customer reviewing final pricing. Competitor quote received - need to address value proposition.",
    confidence: 100,
    actionable: true,
    priority: "critical",
    createdAt: new Date("2026-01-07"),
  },
  {
    id: "i10",
    customerId: "7",
    source: "property-api",
    category: "property",
    title: "Aging Roof System",
    content: "22-year-old 3-tab shingles past expected lifespan. Insurance may require replacement for renewal.",
    confidence: 92,
    actionable: true,
    priority: "high",
    createdAt: new Date("2026-01-04"),
  },
  {
    id: "i11",
    customerId: "7",
    source: "insurance-lookup",
    category: "insurance",
    title: "Farmers - Standard Process",
    content: "Carrier requires documented damage photos. Prepare comprehensive inspection report.",
    confidence: 85,
    actionable: true,
    priority: "medium",
    createdAt: new Date("2026-01-06"),
  },
  {
    id: "i12",
    customerId: "8",
    source: "crm-sync",
    category: "sales",
    title: "Deal Won - Premium Package",
    content: "Customer selected premium architectural shingles with extended warranty. High margin deal.",
    confidence: 100,
    actionable: true,
    priority: "high",
    createdAt: new Date("2026-01-07"),
  },
  {
    id: "i13",
    customerId: "9",
    source: "crm-sync",
    category: "sales",
    title: "Installation Scheduled",
    content: "Full roof replacement confirmed. Crew assigned for Jan 15-17. Materials in transit.",
    confidence: 100,
    actionable: true,
    priority: "high",
    createdAt: new Date("2026-01-05"),
  },
  {
    id: "i14",
    customerId: "10",
    source: "crm-sync",
    category: "sales",
    title: "Lost to Competitor",
    content: "Customer chose ABC Roofing - cited lower price. Consider follow-up in 6 months.",
    confidence: 100,
    actionable: false,
    priority: "low",
    createdAt: new Date("2025-12-20"),
  },
  {
    id: "i15",
    customerId: "11",
    source: "crm-sync",
    category: "sales",
    title: "Decided Not to Proceed",
    content: "Customer postponing roof work. Budget constraints cited. Re-engage in spring.",
    confidence: 100,
    actionable: false,
    priority: "low",
    createdAt: new Date("2025-12-15"),
  },
  {
    id: "i16",
    customerId: "12",
    source: "property-api",
    category: "property",
    title: "Premium Cedar Shake - Specialty Work",
    content: "Cedar shake roof requires specialized crew. High-value restoration opportunity.",
    confidence: 95,
    actionable: true,
    priority: "high",
    createdAt: new Date("2026-01-04"),
  },
  {
    id: "i17",
    customerId: "14",
    source: "property-api",
    category: "property",
    title: "Slate Roof Assessment Needed",
    content: "28-year-old slate roof. Requires specialized inspection. Potential $85K+ project.",
    confidence: 90,
    actionable: true,
    priority: "critical",
    createdAt: new Date("2026-01-07"),
  },
];

export const mockWeatherEvents: WeatherEvent[] = [
  {
    id: "w1",
    customerId: "1",
    eventType: "hail",
    eventDate: new Date("2026-01-02"),
    severity: "severe",
    hailSize: 1.25,
    damageReported: false,
    claimFiled: false,
  },
  {
    id: "w2",
    customerId: "3",
    eventType: "wind",
    eventDate: new Date("2025-12-15"),
    severity: "moderate",
    windSpeed: 58,
    damageReported: false,
    claimFiled: false,
  },
  {
    id: "w3",
    customerId: "3",
    eventType: "hail",
    eventDate: new Date("2025-10-20"),
    severity: "moderate",
    hailSize: 0.75,
    damageReported: false,
    claimFiled: false,
  },
  {
    id: "w4",
    customerId: "5",
    eventType: "wind",
    eventDate: new Date("2025-11-08"),
    severity: "severe",
    windSpeed: 65,
    damageReported: true,
    claimFiled: true,
  },
  // Additional weather events for new customers
  {
    id: "w5",
    customerId: "6",
    eventType: "wind",
    eventDate: new Date("2026-01-04"),
    severity: "moderate",
    windSpeed: 60,
    damageReported: false,
    claimFiled: false,
  },
  {
    id: "w6",
    customerId: "7",
    eventType: "hail",
    eventDate: new Date("2025-12-28"),
    severity: "moderate",
    hailSize: 0.88,
    damageReported: false,
    claimFiled: false,
  },
  {
    id: "w7",
    customerId: "8",
    eventType: "hail",
    eventDate: new Date("2025-12-20"),
    severity: "severe",
    hailSize: 1.5,
    damageReported: true,
    claimFiled: true,
  },
  {
    id: "w8",
    customerId: "9",
    eventType: "wind",
    eventDate: new Date("2025-11-15"),
    severity: "moderate",
    windSpeed: 55,
    damageReported: true,
    claimFiled: true,
  },
  {
    id: "w9",
    customerId: "12",
    eventType: "wind",
    eventDate: new Date("2026-01-03"),
    severity: "moderate",
    windSpeed: 52,
    damageReported: false,
    claimFiled: false,
  },
  {
    id: "w10",
    customerId: "14",
    eventType: "hail",
    eventDate: new Date("2026-01-06"),
    severity: "severe",
    hailSize: 1.75,
    damageReported: false,
    claimFiled: false,
  },
];

export const mockDailyMetrics = {
  newLeads: 12,
  qualifiedLeads: 8,
  callsMade: 47,
  emailsSent: 23,
  visitsMade: 6,
  proposalsSent: 4,
  proposalValue: 87500,
  dealsClosed: 2,
  revenueWon: 34500,
  weatherAlerts: 3,
  stormLeads: 15,
};

export const mockTeamMetrics = [
  { name: "Sarah Mitchell", deals: 8, revenue: 142000, closeRate: 34, calls: 156 },
  { name: "James Rodriguez", deals: 6, revenue: 118000, closeRate: 28, calls: 142 },
  { name: "Emily Thompson", deals: 5, revenue: 95000, closeRate: 25, calls: 128 },
  { name: "Marcus Johnson", deals: 4, revenue: 78000, closeRate: 22, calls: 115 },
];

export const mockPipelineData = [
  { stage: "New Leads", count: 45, value: 675000 },
  { stage: "Contacted", count: 32, value: 512000 },
  { stage: "Qualified", count: 24, value: 456000 },
  { stage: "Proposal", count: 18, value: 378000 },
  { stage: "Negotiation", count: 8, value: 184000 },
  { stage: "Closed Won", count: 12, value: 234000 },
];

export const mockWeeklyTrend = [
  { day: "Mon", leads: 8, calls: 42, deals: 1 },
  { day: "Tue", leads: 12, calls: 56, deals: 2 },
  { day: "Wed", leads: 10, calls: 48, deals: 1 },
  { day: "Thu", leads: 15, calls: 62, deals: 3 },
  { day: "Fri", leads: 11, calls: 51, deals: 2 },
  { day: "Sat", leads: 6, calls: 24, deals: 0 },
  { day: "Sun", leads: 3, calls: 12, deals: 0 },
];
