import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import type { GeneratedDeck } from '../types/deck.types';

export async function exportDeckToPDF(
  deck: GeneratedDeck,
  previewElement: HTMLElement
): Promise<void> {
  // Get the slide preview area (the 16:9 container)
  const slidePreview = previewElement.querySelector('[data-slide-preview]') as HTMLElement;

  if (!slidePreview) {
    throw new Error('Slide preview element not found');
  }

  const pdf = new jsPDF({
    orientation: 'landscape',
    unit: 'px',
    format: [1280, 720] // 16:9 aspect ratio at reasonable resolution
  });

  const totalSlides = deck.slides.length;

  // We need to capture each slide by navigating through them
  // For now, capture the current visible slide and create a single-page PDF
  // A full implementation would render all slides off-screen

  const canvas = await html2canvas(slidePreview, {
    scale: 2,
    useCORS: true,
    backgroundColor: '#0f0f1a', // Match dark theme background
    logging: false,
  });

  const imgData = canvas.toDataURL('image/png');
  const pdfWidth = pdf.internal.pageSize.getWidth();
  const pdfHeight = pdf.internal.pageSize.getHeight();

  pdf.addImage(imgData, 'PNG', 0, 0, pdfWidth, pdfHeight);

  // Add slide count note
  pdf.setFontSize(10);
  pdf.setTextColor(150, 150, 150);
  pdf.text(`Slide 1 of ${totalSlides} - Generated by Guardian Intel`, 20, pdfHeight - 20);

  const filename = `${deck.templateName.replace(/\s+/g, '-').toLowerCase()}-${new Date().toISOString().split('T')[0]}.pdf`;
  pdf.save(filename);
}

// Alternative: Export all slides as a multi-page PDF
// This requires the DeckPreview component to expose a way to render each slide
export async function exportAllSlidesToPDF(
  deck: GeneratedDeck,
  renderSlide: (index: number) => Promise<HTMLElement>
): Promise<void> {
  const pdf = new jsPDF({
    orientation: 'landscape',
    unit: 'px',
    format: [1280, 720]
  });

  for (let i = 0; i < deck.slides.length; i++) {
    const slideElement = await renderSlide(i);

    const canvas = await html2canvas(slideElement, {
      scale: 2,
      useCORS: true,
      backgroundColor: '#0f0f1a',
      logging: false,
    });

    const imgData = canvas.toDataURL('image/png');
    const pdfWidth = pdf.internal.pageSize.getWidth();
    const pdfHeight = pdf.internal.pageSize.getHeight();

    if (i > 0) {
      pdf.addPage();
    }

    pdf.addImage(imgData, 'PNG', 0, 0, pdfWidth, pdfHeight);
  }

  const filename = `${deck.templateName.replace(/\s+/g, '-').toLowerCase()}-${new Date().toISOString().split('T')[0]}.pdf`;
  pdf.save(filename);
}
