"use client";

import { useState, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { useRouter } from "next/navigation";
import { X, CloudLightning, MapPin, Calendar, Users, FileText, Zap, Cloud, AlertTriangle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { useToast } from "@/components/ui/toast";
import { formatCurrency } from "@/lib/utils";
import {
  StormEvent,
  ForecastData,
  TabId,
  stormTypeIcons,
  severityColors,
  locationCoords,
  mockAffectedCustomers,
} from "./storm-details/types";
import { StormOverviewTab } from "./storm-details/storm-overview-tab";
import { StormForecastTab } from "./storm-details/storm-forecast-tab";
import { StormAlertsTab } from "./storm-details/storm-alerts-tab";

interface StormDetailsModalProps {
  isOpen: boolean;
  onClose: () => void;
  event: StormEvent | null;
}

const tabs: { id: TabId; label: string; icon: typeof Users }[] = [
  { id: "overview", label: "Overview", icon: Users },
  { id: "forecast", label: "Weather Forecast", icon: Cloud },
  { id: "alerts", label: "Alert Details", icon: AlertTriangle },
];

export function StormDetailsModal({ isOpen, onClose, event }: StormDetailsModalProps) {
  const router = useRouter();
  const { showToast } = useToast();
  const [activeTab, setActiveTab] = useState<TabId>("overview");
  const [forecast, setForecast] = useState<ForecastData | null>(null);
  const [isLoadingForecast, setIsLoadingForecast] = useState(false);
  const [forecastError, setForecastError] = useState<string | null>(null);

  const coords = event ? locationCoords[event.location] || { lat: 40.1773, lon: -75.0035, state: "PA" } : null;

  useEffect(() => {
    if (isOpen && event && (activeTab === "forecast" || activeTab === "alerts") && !forecast && !isLoadingForecast) {
      fetchForecast();
    }
  }, [isOpen, event, activeTab]);

  useEffect(() => {
    if (!isOpen) {
      setActiveTab("overview");
      setForecast(null);
      setForecastError(null);
    }
  }, [isOpen]);

  const fetchForecast = async () => {
    if (!coords) return;
    setIsLoadingForecast(true);
    setForecastError(null);
    try {
      const response = await fetch(`/api/weather/forecast?lat=${coords.lat}&lon=${coords.lon}`);
      if (!response.ok) throw new Error("Failed to fetch forecast");
      const data = await response.json();
      setForecast(data);
    } catch (error) {
      console.error("Forecast fetch error:", error);
      setForecastError("Unable to load weather data");
    } finally {
      setIsLoadingForecast(false);
    }
  };

  if (!isOpen || !event) return null;

  const Icon = stormTypeIcons[event.type] || CloudLightning;

  const handleCallCustomer = (name: string, phone: string) => {
    showToast("success", "Calling...", `Dialing ${name} at ${phone}`);
    window.location.href = `tel:${phone}`;
  };

  const handleViewAllCustomers = () => {
    onClose();
    router.push(`/customers?storm=${event.id}`);
  };

  const handleGenerateReport = () => {
    showToast("success", "Report Generated", `Storm report for ${event.location} has been downloaded`);
    const report = `
STORM EVENT REPORT
==================
Date: ${new Date(event.date).toLocaleDateString()}
Location: ${event.location} (${event.county} County)
Type: ${event.type.toUpperCase()}
Severity: ${event.severity.toUpperCase()}
${event.hailSize ? `Hail Size: ${event.hailSize}"` : ""}
${event.windSpeed ? `Wind Speed: ${event.windSpeed} mph` : ""}

IMPACT SUMMARY
--------------
Affected Customers: ${event.affectedCustomers}
Inspections Pending: ${event.inspectionsPending}
Claims Filed: ${event.claimsFiled}
Estimated Opportunity: ${formatCurrency(event.opportunity)}

Generated by Guardian Intel on ${new Date().toLocaleString()}
    `.trim();
    const blob = new Blob([report], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `storm-report-${event.id}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleStartCanvass = () => {
    showToast("success", "Canvass Started", `Starting storm canvass for ${event.location}`);
    onClose();
    router.push(`/customers?storm=${event.id}&action=canvass`);
  };

  const openNWSForecast = () => {
    if (coords) window.open(`https://forecast.weather.gov/MapClick.php?lat=${coords.lat}&lon=${coords.lon}`, "_blank");
  };

  const openNWSRadar = () => {
    if (coords) window.open(`https://radar.weather.gov/?settings=v1_eyJhZ2VuZGEiOnsiaWQiOiJsb2NhbCIsImNlbnRlciI6Wy03NS4wMDM1LDQwLjE3NzNdLCJ6b29tIjo4fX0%3D#/`, "_blank");
  };

  const openNOAAStormEvents = () => {
    const stateCode = coords?.state || "PA";
    window.open(`https://www.ncdc.noaa.gov/stormevents/choosedates.jsp?statefips=${stateCode}`, "_blank");
  };

  return (
    <AnimatePresence>
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
        className="fixed top-0 left-0 w-screen h-screen bg-black/60 backdrop-blur-sm z-[9999] flex items-center justify-center p-4"
        onClick={onClose}
      >
        <motion.div
          initial={{ opacity: 0, scale: 0.95, y: 20 }}
          animate={{ opacity: 1, scale: 1, y: 0 }}
          exit={{ opacity: 0, scale: 0.95, y: 20 }}
          className="w-full max-w-4xl bg-[hsl(var(--surface-primary))] border border-border rounded-lg shadow-2xl overflow-hidden max-h-[90vh] flex flex-col"
          onClick={e => e.stopPropagation()}
        >
          {/* Header */}
          <div className={`p-5 border-b border-border ${event.severity === "severe" ? "bg-rose-500/5" : "bg-amber-500/5"}`}>
            <div className="flex items-start justify-between">
              <div className="flex items-start gap-4">
                <div className={`w-14 h-14 rounded-xl flex items-center justify-center ${event.severity === "severe" ? "bg-rose-500/20" : "bg-amber-500/20"}`}>
                  <Icon className={`w-7 h-7 ${event.severity === "severe" ? "text-rose-400" : "text-amber-400"}`} />
                </div>
                <div>
                  <div className="flex items-center gap-2 mb-1">
                    <h2 className="font-display font-bold text-xl text-text-primary capitalize">{event.type} Event</h2>
                    <Badge className={severityColors[event.severity]}>{event.severity}</Badge>
                  </div>
                  <div className="flex items-center gap-4 text-sm text-text-muted">
                    <span className="flex items-center gap-1"><MapPin className="w-4 h-4" />{event.location} ({event.county} County)</span>
                    <span className="flex items-center gap-1"><Calendar className="w-4 h-4" />{new Date(event.date).toLocaleDateString()}</span>
                  </div>
                </div>
              </div>
              <button onClick={onClose} className="p-2 hover:bg-surface-hover rounded transition-colors">
                <X className="w-5 h-5 text-text-muted" />
              </button>
            </div>
          </div>

          {/* Tabs */}
          <div className="flex border-b border-border">
            {tabs.map((tab) => (
              <button
                key={tab.id}
                onClick={() => setActiveTab(tab.id)}
                className={`flex items-center gap-2 px-5 py-3 text-sm font-medium transition-colors ${
                  activeTab === tab.id
                    ? "text-accent-primary border-b-2 border-accent-primary bg-accent-primary/5"
                    : "text-text-muted hover:text-text-primary hover:bg-surface-hover"
                }`}
              >
                <tab.icon className="w-4 h-4" />
                {tab.label}
              </button>
            ))}
          </div>

          {/* Tab Content */}
          <div className="flex-1 overflow-y-auto">
            {activeTab === "overview" && (
              <StormOverviewTab
                event={event}
                affectedCustomers={mockAffectedCustomers}
                onCallCustomer={handleCallCustomer}
                onViewAllCustomers={handleViewAllCustomers}
              />
            )}
            {activeTab === "forecast" && (
              <StormForecastTab
                event={event}
                forecast={forecast}
                isLoading={isLoadingForecast}
                error={forecastError}
                onRetry={fetchForecast}
                onOpenNWSForecast={openNWSForecast}
                onOpenNWSRadar={openNWSRadar}
                onOpenNOAAStormEvents={openNOAAStormEvents}
              />
            )}
            {activeTab === "alerts" && (
              <StormAlertsTab
                forecast={forecast}
                isLoading={isLoadingForecast}
                onOpenNWSForecast={openNWSForecast}
                onOpenNOAAStormEvents={openNOAAStormEvents}
              />
            )}
          </div>

          {/* Footer Actions */}
          <div className="flex items-center justify-between p-4 border-t border-border bg-surface-secondary/30">
            <Button variant="outline" onClick={handleGenerateReport}>
              <FileText className="w-4 h-4" />
              Generate Report
            </Button>
            <div className="flex gap-2">
              <Button variant="outline" onClick={handleViewAllCustomers}>
                <Users className="w-4 h-4" />
                View All Customers
              </Button>
              <Button onClick={handleStartCanvass}>
                <Zap className="w-4 h-4" />
                Start Canvass
              </Button>
            </div>
          </div>
        </motion.div>
      </motion.div>
    </AnimatePresence>
  );
}

export type { StormEvent } from "./storm-details/types";
