"use client";

import { motion, AnimatePresence } from "framer-motion";
import { useRouter } from "next/navigation";
import {
  X,
  CloudLightning,
  MapPin,
  Calendar,
  Users,
  Phone,
  DollarSign,
  AlertTriangle,
  Wind,
  CloudRain,
  Zap,
  FileText,
  ExternalLink,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { useToast } from "@/components/ui/toast";
import { formatCurrency } from "@/lib/utils";

interface StormEvent {
  id: string;
  type: string;
  date: Date;
  location: string;
  county: string;
  hailSize?: number;
  windSpeed?: number;
  severity: string;
  affectedCustomers: number;
  inspectionsPending: number;
  claimsFiled: number;
  opportunity: number;
}

interface StormDetailsModalProps {
  isOpen: boolean;
  onClose: () => void;
  event: StormEvent | null;
}

const stormTypeIcons: Record<string, typeof CloudLightning> = {
  hail: CloudRain,
  wind: Wind,
  thunderstorm: Zap,
  tornado: CloudLightning,
};

const severityColors: Record<string, string> = {
  minor: "bg-guardian-500/20 text-guardian-400 border-guardian-500/30",
  moderate: "bg-amber-500/20 text-amber-400 border-amber-500/30",
  severe: "bg-rose-500/20 text-rose-400 border-rose-500/30",
  catastrophic: "bg-purple-500/20 text-purple-400 border-purple-500/30",
};

// Mock affected customers for this storm
const mockAffectedCustomers = [
  { id: "1", name: "Robert Chen", address: "123 Oak Lane", phone: "(555) 234-5678", status: "pending_inspection" },
  { id: "2", name: "Michael Davis", address: "456 Elm Street", phone: "(555) 345-6789", status: "claim_filed" },
  { id: "3", name: "Jennifer Walsh", address: "789 Pine Ave", phone: "(555) 456-7890", status: "contacted" },
  { id: "4", name: "Thomas Anderson", address: "321 Maple Dr", phone: "(555) 567-8901", status: "not_contacted" },
  { id: "5", name: "Patricia Williams", address: "654 Cedar Blvd", phone: "(555) 678-9012", status: "not_contacted" },
];

const statusLabels: Record<string, { label: string; color: string }> = {
  not_contacted: { label: "Not Contacted", color: "bg-surface-500/20 text-surface-400" },
  contacted: { label: "Contacted", color: "bg-blue-500/20 text-blue-400" },
  pending_inspection: { label: "Pending Inspection", color: "bg-amber-500/20 text-amber-400" },
  claim_filed: { label: "Claim Filed", color: "bg-emerald-500/20 text-emerald-400" },
};

export function StormDetailsModal({ isOpen, onClose, event }: StormDetailsModalProps) {
  const router = useRouter();
  const { showToast } = useToast();

  if (!isOpen || !event) return null;

  const Icon = stormTypeIcons[event.type] || CloudLightning;

  const handleCallCustomer = (name: string, phone: string) => {
    showToast("success", "Calling...", `Dialing ${name} at ${phone}`);
    window.location.href = `tel:${phone}`;
  };

  const handleViewAllCustomers = () => {
    onClose();
    router.push(`/customers?storm=${event.id}`);
  };

  const handleGenerateReport = () => {
    showToast("success", "Report Generated", `Storm report for ${event.location} has been downloaded`);
    
    // Generate and download a simple text report
    const report = `
STORM EVENT REPORT
==================
Date: ${event.date.toLocaleDateString()}
Location: ${event.location} (${event.county} County)
Type: ${event.type.toUpperCase()}
Severity: ${event.severity.toUpperCase()}
${event.hailSize ? `Hail Size: ${event.hailSize}"` : ""}
${event.windSpeed ? `Wind Speed: ${event.windSpeed} mph` : ""}

IMPACT SUMMARY
--------------
Affected Customers: ${event.affectedCustomers}
Inspections Pending: ${event.inspectionsPending}
Claims Filed: ${event.claimsFiled}
Estimated Opportunity: ${formatCurrency(event.opportunity)}

Generated by Guardian Intel on ${new Date().toLocaleString()}
    `.trim();
    
    const blob = new Blob([report], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `storm-report-${event.id}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleStartCanvass = () => {
    showToast("success", "Canvass Started", `Starting storm canvass for ${event.location}`);
    onClose();
    router.push(`/customers?storm=${event.id}&action=canvass`);
  };

  return (
    <AnimatePresence>
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
        className="fixed inset-0 bg-black/60 backdrop-blur-sm z-[9999] flex items-center justify-center p-4"
        onClick={onClose}
      >
        <motion.div
          initial={{ opacity: 0, scale: 0.95, y: 20 }}
          animate={{ opacity: 1, scale: 1, y: 0 }}
          exit={{ opacity: 0, scale: 0.95, y: 20 }}
          className="w-full max-w-3xl bg-[hsl(var(--surface-primary))] border border-border rounded-lg shadow-2xl overflow-hidden max-h-[90vh] flex flex-col"
          onClick={e => e.stopPropagation()}
        >
          {/* Header */}
          <div className={`p-5 border-b border-border ${
            event.severity === "severe" ? "bg-rose-500/5" : "bg-amber-500/5"
          }`}>
            <div className="flex items-start justify-between">
              <div className="flex items-start gap-4">
                <div className={`w-14 h-14 rounded-xl flex items-center justify-center ${
                  event.severity === "severe" ? "bg-rose-500/20" : "bg-amber-500/20"
                }`}>
                  <Icon className={`w-7 h-7 ${
                    event.severity === "severe" ? "text-rose-400" : "text-amber-400"
                  }`} />
                </div>
                <div>
                  <div className="flex items-center gap-2 mb-1">
                    <h2 className="font-display font-bold text-xl text-text-primary capitalize">
                      {event.type} Event
                    </h2>
                    <Badge className={severityColors[event.severity]}>
                      {event.severity}
                    </Badge>
                  </div>
                  <div className="flex items-center gap-4 text-sm text-text-muted">
                    <span className="flex items-center gap-1">
                      <MapPin className="w-4 h-4" />
                      {event.location} ({event.county} County)
                    </span>
                    <span className="flex items-center gap-1">
                      <Calendar className="w-4 h-4" />
                      {event.date.toLocaleDateString()}
                    </span>
                  </div>
                </div>
              </div>
              <button onClick={onClose} className="p-2 hover:bg-surface-hover rounded transition-colors">
                <X className="w-5 h-5 text-text-muted" />
              </button>
            </div>
          </div>

          {/* Stats */}
          <div className="grid grid-cols-4 gap-4 p-4 border-b border-border">
            <div className="text-center p-3 bg-surface-secondary/50 rounded-lg">
              {event.hailSize ? (
                <>
                  <div className="text-2xl font-bold text-text-primary">{event.hailSize}"</div>
                  <div className="text-xs text-text-muted">Hail Size</div>
                </>
              ) : event.windSpeed ? (
                <>
                  <div className="text-2xl font-bold text-text-primary">{event.windSpeed}</div>
                  <div className="text-xs text-text-muted">mph Winds</div>
                </>
              ) : (
                <>
                  <div className="text-2xl font-bold text-text-primary">-</div>
                  <div className="text-xs text-text-muted">Metrics</div>
                </>
              )}
            </div>
            <div className="text-center p-3 bg-surface-secondary/50 rounded-lg">
              <div className="text-2xl font-bold text-text-primary">{event.affectedCustomers}</div>
              <div className="text-xs text-text-muted">Customers Affected</div>
            </div>
            <div className="text-center p-3 bg-amber-500/10 rounded-lg">
              <div className="text-2xl font-bold text-amber-400">{event.inspectionsPending}</div>
              <div className="text-xs text-text-muted">Inspections Pending</div>
            </div>
            <div className="text-center p-3 bg-emerald-500/10 rounded-lg">
              <div className="text-2xl font-bold text-emerald-400">{formatCurrency(event.opportunity)}</div>
              <div className="text-xs text-text-muted">Opportunity Value</div>
            </div>
          </div>

          {/* Affected Customers */}
          <div className="flex-1 overflow-y-auto p-4">
            <div className="flex items-center justify-between mb-3">
              <h3 className="font-medium text-text-primary flex items-center gap-2">
                <Users className="w-4 h-4 text-accent-primary" />
                Affected Customers
              </h3>
              <button
                onClick={handleViewAllCustomers}
                className="text-sm text-accent-primary hover:opacity-80 flex items-center gap-1"
              >
                View All
                <ExternalLink className="w-3 h-3" />
              </button>
            </div>
            
            <div className="space-y-2">
              {mockAffectedCustomers.map((customer) => (
                <div
                  key={customer.id}
                  className="flex items-center justify-between p-3 bg-surface-secondary/30 rounded-lg border border-border hover:border-accent-primary/30 transition-colors"
                >
                  <div className="flex items-center gap-3">
                    <div className="w-10 h-10 rounded-full bg-gradient-to-br from-accent-primary/30 to-accent-primary/10 flex items-center justify-center text-sm font-medium text-accent-primary">
                      {customer.name.split(" ").map(n => n[0]).join("")}
                    </div>
                    <div>
                      <p className="text-sm font-medium text-text-primary">{customer.name}</p>
                      <p className="text-xs text-text-muted">{customer.address}</p>
                    </div>
                  </div>
                  <div className="flex items-center gap-2">
                    <Badge className={statusLabels[customer.status].color}>
                      {statusLabels[customer.status].label}
                    </Badge>
                    <button
                      onClick={() => handleCallCustomer(customer.name, customer.phone)}
                      className="p-2 rounded-lg bg-accent-primary/10 text-accent-primary hover:bg-accent-primary/20 transition-colors"
                    >
                      <Phone className="w-4 h-4" />
                    </button>
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Footer Actions */}
          <div className="flex items-center justify-between p-4 border-t border-border bg-surface-secondary/30">
            <Button variant="outline" onClick={handleGenerateReport}>
              <FileText className="w-4 h-4" />
              Generate Report
            </Button>
            <div className="flex gap-2">
              <Button variant="outline" onClick={handleViewAllCustomers}>
                <Users className="w-4 h-4" />
                View All Customers
              </Button>
              <Button onClick={handleStartCanvass}>
                <Zap className="w-4 h-4" />
                Start Canvass
              </Button>
            </div>
          </div>
        </motion.div>
      </motion.div>
    </AnimatePresence>
  );
}
